### ISSUE TITLE
not launching

### ISSUE THREAD

**Issue by 123Pixely** [HiDe-Techno-Tips/yuzu-Early-Access-Launcher#1]
I've used the normal yuzu before but it stopped working so I tried using this one and I click launch and absolutely nothing happens I've checked the task manager and nothing happens

**Comment by HiDe-Techno-Tips** [comment]
what is the version of the launcher?

you can try a shutdown, restart, and then reinstall yuzu early access.

**Comment by HiDe-Techno-Tips** [comment]
or after a restart, you can just right click the yuzu early access launcher shortcut, open file location, there will be a folder named `yuzu-windows-msvc-early-access`. run `yuzu.exe` from inside that folder.

It you run `yuzu.exe`, and

if its an error then delete `yuzu-windows-msvc-early-access` folder, then run the launcher.

if theres no error and it runs, then the launcher will work next time.

**Comment by 123Pixely** [comment]
I just uninstalled it and fully removed the files from my pc then installed
the normal yuzu and it's working again
