### ISSUE TITLE
Can't download latest Yuzu EA versions

### ISSUE THREAD

**Issue by RootManHD** [HiDe-Techno-Tips/yuzu-Early-Access-Launcher#11]
There's a problem with the Yuzu EA launcher, it can't install newer versions. It seems that the archives are damaged 
![Screenshot_2](https://user-images.githubusercontent.com/117686325/200414695-b470b354-9148-4134-aff0-9b0d194edc38.png)

**Comment by tonytziorvas** [comment]
Same Here

**Comment by Creaticx72** [comment]
Same problem.

**Comment by HimDek** [comment]
Duplicate of #10
