### ISSUE TITLE
incorrect ram info

### ISSUE THREAD

**Issue by Samford1** [HiDe-Techno-Tips/yuzu-Early-Access-Launcher#2]
it says i have 8 gb of ram, but i have 16 gb installed. windows also says i have 16gb, so i know its an issue with this software. 

on a side note the download speed of the firmware is incredibly slow compared to the actual program, about 50 - 200 kb/s while the program was 1 - 2 mb/s

**Comment by HiDe-Techno-Tips** [comment]
Open CMD and run the below command:
`wmic memorychip get Capacity /format:list`
For me, I get the output:
`Capacity=8589934592`
It is my amount of RAM that is 8GB in bytes.
If you have 16GB RAM, you should get the below output:
`Capacity=17,179,869,184`
Tell me if its the expected result or not.

For the download speed, I know the Launcher can not perfectly measure it, but you should know that
`1 MBps = 8 Mbps`
The upper case `B` represents a byte.
whereas the lower case `b` represents a bit.
Windows task manager shows speed in `Mbps`, that means if its showing `1 -2 Mbps`, it actually is about `125 - 250 KBps`.
Always check if its `b` or `B` while comparing two data speed.

**Comment by Sophie-bear** [comment]
This isn't just a Samford1 issue. My system with 32GB of memory is detected as having 16GB. Running `wmic memorychip get Capacity /format:list` displays the capacity of both modules in my system as expected, however.

**Comment by HiDe-Techno-Tips** [comment]
@Sophie-bear and @Samford1  This zip file, [RAM check.zip](https://github.com/HiDe-Techno-Tips/yuzu-Early-Access-Launcher/files/6987508/RAM.check.zip) contains two exe files that can check the amount of RAM.
The `1.exe` file uses the same old method used in the Launcher, whereas the `2.exe` file uses a new method.
Please tell me which one shows the correct amount of RAM.

**Comment by Sophie-bear** [comment]
@HiDe-Techno-Tips 1 is correct, 2 is incorrect in the same way the current build is.

**Comment by Samford1** [comment]
1.exe is correct

**Comment by Samford1** [comment]
im getting 8589934592, not the other one. what does this mean?

**Comment by HiDe-Techno-Tips** [comment]
> im getting 8589934592, not the other one. what does this mean?

@Samford1 If this your output for `wmic memorychip get Capacity /format:list`, then it means `8 GiB`

See the Screenshot below:
![Untitled](https://user-images.githubusercontent.com/61367380/129468086-6a056ae1-36af-406d-a48f-6aa79d4c776b.png)

**Comment by HiDe-Techno-Tips** [comment]
> @Sophie-bear and @Samford1 This zip file, [RAM check.zip](https://github.com/HiDe-Techno-Tips/yuzu-Early-Access-Launcher/files/6987508/RAM.check.zip) contains two exe files that can check the amount of RAM.
> The `1.exe` file uses the same old method used in the Launcher, whereas the `2.exe` file uses a new method.
> Please tell me which one shows the correct amount of RAM.

@Sophie-bear and @Samford1, Sorry I made a typo. Actually 1.exe is the new one used in Launcher version 1.1.2 while 2.exe is the old one.

The means that, if 1.exe is correct, the problem must have been solved by now in Launcher version 1.1.2.
The launcher automatically updates itself if you run it.
Thanks for the cooperation.

**Comment by Sophie-bear** [comment]
Yep, that did it.

**Comment by HiDe-Techno-Tips** [comment]
> Yep, that did it.

Good to hear that.

**Comment by HiDe-Techno-Tips** [comment]
I think this was caused because `wmic memorychip get Capacity /format:list` command lists only the first RAM module or Memory Chip.
