### ISSUE TITLE
Installing Firmware

### ISSUE THREAD

**Issue by LeoTeamOnline** [HiDe-Techno-Tips/yuzu-Early-Access-Launcher#4]
The app try to install firmware in nandsystem instead of nand/system
![screen](https://user-images.githubusercontent.com/91162014/141187680-a9d2dcb9-0e56-4a0c-be45-380eed367b74.png)

**Comment by HiDe-Techno-Tips** [comment]
## Working on it!
For now a workaround will be to manually extract the contents of the Firmware zip file to `C:\Users\<your username>\AppData\Roaming\yuzu\nand\system\Contents\registered` folder.
If the launcher downloaded the Firmware, it can be found in `C:\Users\<your username>\AppData\Local\yuzu\` folder.

**Comment by HiDe-Techno-Tips** [comment]
This issue has been fixed in [version 2.0.1](https://github.com/HiDe-Techno-Tips/yuzu-Early-Access-Launcher/releases/tag/v2.0.1)
Any older version of the launcher will auto update itself when run with internet access.

**Comment by LeoTeamOnline** [comment]
![Capture d’écran 2021-11-14 123503](https://user-images.githubusercontent.com/91162014/141679193-d909b37f-9fb1-4da8-92ac-5483ee572e03.png)
There is a new error ^^'
