### ISSUE TITLE
prod.keys are always updated

### ISSUE THREAD

**Issue by TheASVigilante** [HiDe-Techno-Tips/yuzu-Early-Access-Launcher#7]
As said in the title prod.keys are always updated on app launch, it would be if there was an option to disable this since the keys are straight up outdated right now and the launcher breaks my install every time i launch it because of this.

**Comment by HimDek** [comment]
Can you please provide the new keys here?

**Comment by HimDek** [comment]
Updated keys https://github.com/HiDe-Techno-Tips/Nintendo-Switch-Files/commit/902a868b5a6bfaddadc6f96a5580f8b3fb33caa0
